version: '3.8'

services:
  # Our chatbot application
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - APP_PORT=8501
      - DATA_PATH=/app/data
      - FAISS_INDEX_PATH=/app/faiss_index
    ports:
      - "8501:8501"
    # Logging configuration to forward to Logstash
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - logstash
    # Restart policy for robustness
    restart: unless-stopped
    
  # Elasticsearch: search engine used to store logs
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    
  # Logstash: log processing pipeline
  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.3
    volumes:
      - ./logging/logstash/pipeline:/usr/share/logstash/pipeline
      - ./logging/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5044:5044"
      - "5001:5000/tcp"
      - "5002:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    restart: unless-stopped
    
  # Kibana: visualization and management interface
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: unless-stopped
    
  # Filebeat: log shipper for Docker logs
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.3
    user: root
    volumes:
      - ./logging/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - elasticsearch
      - logstash
    restart: unless-stopped
    command: filebeat -e -strict.perms=false

volumes:
  elasticsearch_data: 